import { colors as C, fonts } from '../styles/theme';
const ft = fonts.body;

function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();}

function lakehouse_compare(canvas){const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);const tw=W/3-16;[{x:8,label:'Warehouse',pros:['ACID, Schema','Great BI'],cons:['Expensive','No unstructured'],color:C.blue},{x:W/3+4,label:'Data Lake',pros:['Cheap storage','Any format'],cons:['No ACID','Data swamp'],color:C.purple},{x:2*W/3,label:'Lakehouse',pros:['Cheap + ACID','BI + ML unified'],cons:['Newer ecosystem'],color:C.gold}].forEach(col=>{ctx.fillStyle=col.color+'18';ctx.strokeStyle=col.color;ctx.lineWidth=1.5;roundRect(ctx,col.x,20,tw,H-30,10);ctx.fill();ctx.stroke();ctx.fillStyle=C.cream;ctx.font=`bold 12px ${ft}`;ctx.textAlign='center';ctx.fillText(col.label,col.x+tw/2,40);ctx.fillStyle=C.green;ctx.font=`11px ${ft}`;col.pros.forEach((p,i)=>ctx.fillText('✓ '+p,col.x+tw/2,62+i*16));ctx.fillStyle=C.red;col.cons.forEach((p,i)=>ctx.fillText('✗ '+p,col.x+tw/2,100+i*16));});ctx.textAlign='left';}

function delta_log(canvas){const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);const entries=[{ver:'v0',op:'CREATE TABLE',detail:'schema: [order_id, amount, date]',files:'+3 files',color:C.blue},{ver:'v1',op:'INSERT',detail:'2,400 new orders ingested',files:'+2 files',color:C.green},{ver:'v2',op:'UPDATE',detail:'Fix currency for EUR orders',files:'-1 +1 files',color:C.gold},{ver:'v3',op:'MERGE',detail:'CDC from source DB',files:'-2 +2 files',color:C.purple},{ver:'v4',op:'OPTIMIZE',detail:'Compact small files',files:'-8 +2 files',color:C.accent}];const startY=18,rowH=(H-36)/entries.length;ctx.fillStyle=C.creamF;ctx.font=`bold 10px ${ft}`;ctx.textAlign='left';ctx.fillText('_delta_log/',14,14);ctx.strokeStyle=C.bd;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(50,startY+10);ctx.lineTo(50,startY+entries.length*rowH-10);ctx.stroke();entries.forEach((e,i)=>{const y=startY+i*rowH+rowH/2;ctx.beginPath();ctx.arc(50,y,8,0,Math.PI*2);ctx.fillStyle=e.color;ctx.fill();ctx.fillStyle=C.bg;ctx.font=`bold 8px ${ft}`;ctx.textAlign='center';ctx.fillText(e.ver,50,y+3);const cx=72;ctx.fillStyle=e.color+'12';ctx.strokeStyle=e.color+'50';ctx.lineWidth=1;roundRect(ctx,cx,y-18,W-cx-14,36,8);ctx.fill();ctx.stroke();ctx.textAlign='left';ctx.fillStyle=e.color;ctx.font=`bold 11px ${ft}`;ctx.fillText(e.op,cx+10,y-3);ctx.fillStyle=C.creamD;ctx.font=`10px ${ft}`;ctx.fillText(e.detail,cx+10,y+11);ctx.fillStyle=C.creamF;ctx.font=`9px ${ft}`;ctx.textAlign='right';ctx.fillText(e.files,W-22,y+3);});ctx.textAlign='left';}

function spark_distribute(canvas){const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);const dx=W*.12,dy=H*.5;ctx.fillStyle=C.gold+'22';ctx.strokeStyle=C.gold;ctx.lineWidth=2;roundRect(ctx,dx-36,dy-24,72,48,10);ctx.fill();ctx.stroke();ctx.fillStyle=C.gold;ctx.font=`bold 11px ${ft}`;ctx.textAlign='center';ctx.fillText('DRIVER',dx,dy-6);ctx.fillStyle=C.creamF;ctx.font=`9px ${ft}`;ctx.fillText('(notebook)',dx,dy+10);const execs=[{y:.2,label:'Executor 1',p:'Part 1-5'},{y:.42,label:'Executor 2',p:'Part 6-10'},{y:.62,label:'Executor 3',p:'Part 11-15'},{y:.82,label:'Executor 4',p:'Part 16-20'}];const ex=W*.52;execs.forEach(e=>{const ey=e.y*H;ctx.beginPath();ctx.moveTo(dx+36,dy);ctx.lineTo(ex-32,ey);ctx.strokeStyle=C.bd;ctx.lineWidth=1;ctx.setLineDash([3,3]);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=C.blue+'18';ctx.strokeStyle=C.blue;ctx.lineWidth=1.5;roundRect(ctx,ex-32,ey-16,100,32,8);ctx.fill();ctx.stroke();ctx.fillStyle=C.cream;ctx.font=`bold 10px ${ft}`;ctx.textAlign='center';ctx.fillText(e.label,ex+18,ey-1);ctx.fillStyle=C.creamF;ctx.font=`9px ${ft}`;ctx.fillText(e.p,ex+18,ey+12);});const rx=W*.84,ry=H*.5;execs.forEach(e=>{ctx.beginPath();ctx.moveTo(ex+68,e.y*H);ctx.lineTo(rx-30,ry);ctx.strokeStyle=C.green+'60';ctx.lineWidth=1;ctx.setLineDash([3,3]);ctx.stroke();ctx.setLineDash([]);});ctx.fillStyle=C.green+'22';ctx.strokeStyle=C.green;ctx.lineWidth=2;roundRect(ctx,rx-30,ry-20,60,40,10);ctx.fill();ctx.stroke();ctx.fillStyle=C.green;ctx.font=`bold 10px ${ft}`;ctx.textAlign='center';ctx.fillText('RESULT',rx,ry+4);ctx.fillStyle=C.creamF;ctx.font=`10px ${ft}`;ctx.fillText('2TB → 20 partitions → 4 executors → combined result',W/2,H-8);ctx.textAlign='left';}

function unity_catalog(canvas){const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);const levels=[{label:'METASTORE',items:['company_metastore'],y:.12,color:C.gold},{label:'CATALOG',items:['production','staging','sandbox'],y:.36,color:C.blue},{label:'SCHEMA',items:['finance','ml_features','marketing'],y:.6,color:C.purple},{label:'TABLE',items:['transactions','user_embed','campaigns'],y:.84,color:C.green}];levels.forEach(lv=>{const y=lv.y*H;ctx.fillStyle=lv.color;ctx.font=`bold 9px ${ft}`;ctx.textAlign='left';ctx.fillText(lv.label,10,y+4);const totalW=W-90,itemW=Math.min(totalW/lv.items.length-6,.25*W),startX=88;lv.items.forEach((item,i)=>{const ix=startX+i*(itemW+6);ctx.fillStyle=lv.color+'18';ctx.strokeStyle=lv.color+'60';ctx.lineWidth=1;roundRect(ctx,ix,y-12,itemW,24,6);ctx.fill();ctx.stroke();ctx.fillStyle=C.cream;ctx.font=`10px ${ft}`;ctx.textAlign='center';ctx.fillText(item,ix+itemW/2,y+3);});});for(let i=0;i<levels.length-1;i++){ctx.beginPath();ctx.moveTo(W/2,levels[i].y*H+14);ctx.lineTo(W/2,levels[i+1].y*H-14);ctx.strokeStyle=C.bd;ctx.lineWidth=1;ctx.setLineDash([4,3]);ctx.stroke();ctx.setLineDash([]);}ctx.textAlign='center';ctx.fillStyle=C.creamF;ctx.font=`10px ${ft}`;ctx.fillText('production.finance.transactions',W/2,H-6);ctx.textAlign='left';}

function dlt_pipeline(canvas){const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);const nodes=[{x:.08,y:.3,label:'Raw JSON',sub:'Auto Loader',color:C.creamF,w:76,h:40},{x:.08,y:.7,label:'Raw CSV',sub:'Auto Loader',color:C.creamF,w:76,h:40},{x:.35,y:.3,label:'bronze_orders',sub:'STREAMING',color:'#a07040',w:100,h:40},{x:.35,y:.7,label:'bronze_users',sub:'STREAMING',color:'#a07040',w:100,h:40},{x:.62,y:.4,label:'silver_orders',sub:'3 expectations',color:'#8090a0',w:100,h:40},{x:.62,y:.72,label:'silver_users',sub:'2 expectations',color:'#8090a0',w:100,h:40},{x:.88,y:.5,label:'gold_revenue',sub:'MATERIALIZED',color:C.gold,w:96,h:40}];const edges=[[0,2],[1,3],[2,4],[3,5],[3,4],[4,6],[5,6]];edges.forEach(e=>{const a=nodes[e[0]],b=nodes[e[1]];ctx.beginPath();ctx.moveTo(a.x*W+a.w/2,a.y*H);ctx.lineTo(b.x*W-b.w/2,b.y*H);ctx.strokeStyle=C.bd;ctx.lineWidth=1.5;ctx.setLineDash([4,3]);ctx.stroke();ctx.setLineDash([]);});nodes.forEach(n=>{const x=n.x*W-n.w/2,y=n.y*H-n.h/2;ctx.fillStyle=n.color+'18';ctx.strokeStyle=n.color;ctx.lineWidth=1.5;roundRect(ctx,x,y,n.w,n.h,8);ctx.fill();ctx.stroke();ctx.fillStyle=C.cream;ctx.font=`bold 10px ${ft}`;ctx.textAlign='center';ctx.fillText(n.label,n.x*W,n.y*H-2);ctx.fillStyle=C.creamF;ctx.font=`8px ${ft}`;ctx.fillText(n.sub,n.x*W,n.y*H+11);});ctx.textAlign='center';ctx.fillStyle=C.creamF;ctx.font=`10px ${ft}`;ctx.fillText('DLT auto-resolves dependencies — you declare tables, it builds the DAG',W/2,H-6);ctx.textAlign='left';}

function data_layout(canvas){const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);const tw=W/3-12;[{x:6,label:'No Optimization',scan:'5 TB scanned',time:'4 min',color:C.red},{x:W/3+2,label:'Partitioned',scan:'400 GB scanned',time:'25 sec',color:C.gold},{x:2*W/3-2,label:'Z-Ordered',scan:'50 GB scanned',time:'3 sec',color:C.green}].forEach(col=>{ctx.fillStyle=col.color+'12';ctx.strokeStyle=col.color+'50';ctx.lineWidth=1.5;roundRect(ctx,col.x,16,tw,H-26,10);ctx.fill();ctx.stroke();ctx.fillStyle=C.cream;ctx.font=`bold 12px ${ft}`;ctx.textAlign='center';ctx.fillText(col.label,col.x+tw/2,36);const bh=10,bw=18,c2=4,rows=5,bx0=col.x+(tw-c2*(bw+3))/2,by0=50;for(let r=0;r<rows;r++)for(let c=0;c<c2;c++){const fx=bx0+c*(bw+3),fy=by0+r*(bh+3);const sc=col.label==='No Optimization'||(col.label==='Partitioned'&&r<2)||(col.label==='Z-Ordered'&&r===0&&c<2);ctx.fillStyle=sc?col.color+'55':C.bd+'40';roundRect(ctx,fx,fy,bw,bh,2);ctx.fill();}ctx.fillStyle=col.color;ctx.font=`bold 11px ${ft}`;ctx.fillText(col.scan,col.x+tw/2,H-36);ctx.fillStyle=C.cream;ctx.font=`bold 14px ${ft}`;ctx.fillText(col.time,col.x+tw/2,H-18);});ctx.textAlign='left';}

function ml_lifecycle(canvas){const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);const steps=[{x:.5,y:.12,label:'DATA PREP',sub:'Features',color:C.blue},{x:.85,y:.3,label:'TRAIN',sub:'MLflow',color:C.purple},{x:.85,y:.62,label:'EVALUATE',sub:'Compare',color:C.gold},{x:.5,y:.8,label:'REGISTER',sub:'Registry',color:C.green},{x:.15,y:.62,label:'SERVE',sub:'Endpoint',color:C.red},{x:.15,y:.3,label:'MONITOR',sub:'Drift',color:C.accent}];for(let i=0;i<steps.length;i++){const a=steps[i],b=steps[(i+1)%steps.length];ctx.beginPath();ctx.moveTo(a.x*W,a.y*H);ctx.lineTo(b.x*W,b.y*H);ctx.strokeStyle=C.bd;ctx.lineWidth=1.5;ctx.setLineDash([4,3]);ctx.stroke();ctx.setLineDash([]);}steps.forEach(s=>{ctx.beginPath();ctx.arc(s.x*W,s.y*H,26,0,Math.PI*2);ctx.fillStyle=s.color+'22';ctx.fill();ctx.strokeStyle=s.color;ctx.lineWidth=2;ctx.stroke();ctx.fillStyle=C.cream;ctx.font=`bold 10px ${ft}`;ctx.textAlign='center';ctx.fillText(s.label,s.x*W,s.y*H-2);ctx.fillStyle=C.creamF;ctx.font=`9px ${ft}`;ctx.fillText(s.sub,s.x*W,s.y*H+10);});ctx.fillStyle=C.creamF;ctx.font=`10px ${ft}`;ctx.fillText('Continuous ML lifecycle — MLflow orchestrates each stage',W/2,H-6);ctx.textAlign='left';}

export const databricksVisualizations = { lakehouse_compare, delta_log, spark_distribute, unity_catalog, dlt_pipeline, data_layout, ml_lifecycle };