import { colors as C, fonts } from '../styles/theme';
const ft = fonts.body;

function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();}

function devops_lifecycle(canvas){const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);const steps=[{x:.5,y:.1,label:'PLAN',color:C.blue},{x:.82,y:.22,label:'CODE',color:C.purple},{x:.95,y:.5,label:'BUILD',color:C.gold},{x:.82,y:.78,label:'TEST',color:C.green},{x:.5,y:.9,label:'RELEASE',color:C.accent},{x:.18,y:.78,label:'DEPLOY',color:C.red},{x:.05,y:.5,label:'OPERATE',color:C.blue},{x:.18,y:.22,label:'MONITOR',color:C.purple}];for(let i=0;i<steps.length;i++){const a=steps[i],b=steps[(i+1)%steps.length];ctx.beginPath();ctx.moveTo(a.x*W,a.y*H);ctx.lineTo(b.x*W,b.y*H);ctx.strokeStyle=C.bd;ctx.lineWidth=1.5;ctx.setLineDash([4,3]);ctx.stroke();ctx.setLineDash([]);}steps.forEach(s=>{ctx.beginPath();ctx.arc(s.x*W,s.y*H,22,0,Math.PI*2);ctx.fillStyle=s.color+'22';ctx.fill();ctx.strokeStyle=s.color;ctx.lineWidth=2;ctx.stroke();ctx.fillStyle=C.cream;ctx.font=`bold 9px ${ft}`;ctx.textAlign='center';ctx.fillText(s.label,s.x*W,s.y*H+3);});ctx.fillStyle=C.creamD;ctx.font=`bold 10px ${ft}`;ctx.fillText('DEV',W*.65,H*.15);ctx.fillText('OPS',W*.15,H*.55);ctx.fillStyle=C.creamF;ctx.font=`10px ${ft}`;ctx.fillText('Continuous loop — feedback from Ops feeds back into Dev',W/2,H-6);ctx.textAlign='left';}

function vm_vs_container(canvas){const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);const hw=W/2-10;ctx.fillStyle=C.cream;ctx.font=`bold 12px ${ft}`;ctx.textAlign='center';ctx.fillText('Virtual Machines',hw/2,16);const vmL=[{label:'App A',h:22,color:C.blue},{label:'Libs/Bins',h:16,color:C.blue+'80'},{label:'Guest OS (2-10 GB)',h:28,color:C.red},{label:'Hypervisor',h:16,color:C.gold},{label:'Host OS + Hardware',h:24,color:C.creamF}];let vy=28;vmL.forEach(l=>{ctx.fillStyle=l.color+'22';ctx.strokeStyle=l.color;ctx.lineWidth=1;roundRect(ctx,8,vy,hw-16,l.h,4);ctx.fill();ctx.stroke();ctx.fillStyle=C.cream;ctx.font=`10px ${ft}`;ctx.textAlign='center';ctx.fillText(l.label,hw/2,vy+l.h/2+3);vy+=l.h+2;});ctx.fillStyle=C.red;ctx.font=`bold 10px ${ft}`;ctx.fillText('Heavy: 2-10 GB each',hw/2,H-8);const cx=hw+20;ctx.fillStyle=C.cream;ctx.font=`bold 12px ${ft}`;ctx.fillText('Containers',cx+hw/2,16);const cL=[{label:'App A',h:22,color:C.green},{label:'Libs only',h:12,color:C.green+'80'},{label:'App B',h:22,color:C.purple},{label:'Libs only',h:12,color:C.purple+'80'},{label:'Container Runtime',h:16,color:C.gold},{label:'Host OS + Hardware',h:24,color:C.creamF}];let cy=28;cL.forEach(l=>{ctx.fillStyle=l.color+'22';ctx.strokeStyle=l.color;ctx.lineWidth=1;roundRect(ctx,cx+8,cy,hw-16,l.h,4);ctx.fill();ctx.stroke();ctx.fillStyle=C.cream;ctx.font=`10px ${ft}`;ctx.textAlign='center';ctx.fillText(l.label,cx+hw/2,cy+l.h/2+3);cy+=l.h+2;});ctx.fillStyle=C.green;ctx.font=`bold 10px ${ft}`;ctx.fillText('Light: 50-500 MB each',cx+hw/2,H-8);ctx.textAlign='left';}

function k8s_architecture(canvas){const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);ctx.fillStyle=C.gold+'10';ctx.strokeStyle=C.gold+'40';ctx.lineWidth=1;roundRect(ctx,6,6,W*.35,H-12,10);ctx.fill();ctx.stroke();ctx.fillStyle=C.gold;ctx.font=`bold 10px ${ft}`;ctx.textAlign='center';ctx.fillText('CONTROL PLANE',W*.18,22);[{label:'API Server',y:.22},{label:'Scheduler',y:.4},{label:'Controller',y:.58},{label:'etcd',y:.76}].forEach(c=>{const y=c.y*H;ctx.fillStyle=C.gold+'22';ctx.strokeStyle=C.gold;ctx.lineWidth=1;roundRect(ctx,16,y,W*.3,20,5);ctx.fill();ctx.stroke();ctx.fillStyle=C.cream;ctx.font=`10px ${ft}`;ctx.fillText(c.label,W*.18,y+13);});for(let n=0;n<2;n++){const nx=W*.42+n*W*.28;ctx.fillStyle=C.blue+'10';ctx.strokeStyle=C.blue+'40';roundRect(ctx,nx,6,W*.26,H-12,10);ctx.fill();ctx.stroke();ctx.fillStyle=C.blue;ctx.font=`bold 10px ${ft}`;ctx.fillText('NODE '+(n+1),nx+W*.13,22);[{label:'kubelet',y:.24},{label:'Pod 📦',y:.44},{label:'Pod 📦',y:.6},{label:'kube-proxy',y:.78}].forEach(p=>{const y=p.y*H;const isPod=p.label.indexOf('Pod')>=0;ctx.fillStyle=(isPod?C.green:C.purple)+'22';ctx.strokeStyle=isPod?C.green:C.purple;roundRect(ctx,nx+10,y,W*.22,18,4);ctx.fill();ctx.stroke();ctx.fillStyle=C.cream;ctx.font=`9px ${ft}`;ctx.fillText(p.label,nx+W*.13,y+12);});}ctx.textAlign='left';}

function cicd_pipeline(canvas){const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);const stages=[{x:.06,label:'Commit',color:C.creamF},{x:.2,label:'Build',color:C.blue},{x:.34,label:'Test',color:C.green},{x:.48,label:'Scan',color:C.purple},{x:.62,label:'Package',color:C.gold},{x:.76,label:'Deploy',color:C.red},{x:.92,label:'Verify',color:C.accent}];ctx.fillStyle=C.blue+'20';roundRect(ctx,W*.02,8,W*.55,H-16,8);ctx.fill();ctx.fillStyle=C.green+'15';roundRect(ctx,W*.58,8,W*.4,H-16,8);ctx.fill();ctx.fillStyle=C.blue;ctx.font=`bold 9px ${ft}`;ctx.textAlign='left';ctx.fillText('CI',14,22);ctx.fillStyle=C.green;ctx.fillText('CD',W*.6,22);stages.forEach((s,i)=>{const x=s.x*W+20,y=H*.52;if(i>0){ctx.beginPath();ctx.moveTo(stages[i-1].x*W+54,y);ctx.lineTo(x-6,y);ctx.strokeStyle=C.bd;ctx.lineWidth=1.5;ctx.setLineDash([3,3]);ctx.stroke();ctx.setLineDash([]);}ctx.beginPath();ctx.arc(x+14,y,18,0,Math.PI*2);ctx.fillStyle=s.color+'22';ctx.fill();ctx.strokeStyle=s.color;ctx.lineWidth=1.5;ctx.stroke();ctx.fillStyle=s.color;ctx.font=`bold 9px ${ft}`;ctx.textAlign='center';ctx.fillText(s.label,x+14,y+28);});ctx.textAlign='left';}

function terraform_flow(canvas){const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);const steps=[{x:.12,y:.4,label:'WRITE',sub:'.tf files',color:C.blue},{x:.37,y:.4,label:'PLAN',sub:'preview',color:C.gold},{x:.62,y:.4,label:'APPLY',sub:'execute',color:C.green},{x:.87,y:.4,label:'STATE',sub:'track',color:C.purple}];steps.forEach((s,i)=>{const x=s.x*W,y=s.y*H;if(i>0){ctx.beginPath();ctx.moveTo(steps[i-1].x*W+40,y);ctx.lineTo(x-40,y);ctx.strokeStyle=C.bd;ctx.lineWidth=1.5;ctx.setLineDash([4,3]);ctx.stroke();ctx.setLineDash([]);}ctx.fillStyle=s.color+'22';ctx.strokeStyle=s.color;ctx.lineWidth=2;roundRect(ctx,x-36,y-28,72,56,10);ctx.fill();ctx.stroke();ctx.fillStyle=C.cream;ctx.font=`bold 10px ${ft}`;ctx.textAlign='center';ctx.fillText(s.label,x,y+2);ctx.fillStyle=C.creamF;ctx.font=`9px ${ft}`;ctx.fillText(s.sub,x,y+16);});ctx.beginPath();ctx.moveTo(W*.87,H*.58);ctx.quadraticCurveTo(W*.5,H*.85,W*.12,H*.58);ctx.strokeStyle=C.bd;ctx.lineWidth=1;ctx.setLineDash([4,3]);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=C.creamF;ctx.font=`9px ${ft}`;ctx.textAlign='center';ctx.fillText('drift detected → update code → repeat',W*.5,H*.82);ctx.textAlign='left';}

function observability_pillars(canvas){const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);const tw=W/3-12;[{x:6,label:'METRICS',sub:'Numbers over time',tool:'Prometheus',color:C.blue},{x:W/3+2,label:'LOGS',sub:'Event records',tool:'ELK / Loki',color:C.gold},{x:2*W/3-2,label:'TRACES',sub:'Request journey',tool:'Jaeger',color:C.green}].forEach(p=>{ctx.fillStyle=p.color+'12';ctx.strokeStyle=p.color+'50';ctx.lineWidth=1.5;roundRect(ctx,p.x,14,tw,H-24,10);ctx.fill();ctx.stroke();ctx.fillStyle=p.color;ctx.font=`bold 12px ${ft}`;ctx.textAlign='center';ctx.fillText(p.label,p.x+tw/2,36);ctx.fillStyle=C.creamD;ctx.font=`11px ${ft}`;ctx.fillText(p.sub,p.x+tw/2,54);ctx.fillStyle=p.color;ctx.font=`bold 10px ${ft}`;ctx.fillText(p.tool,p.x+tw/2,H-18);});ctx.textAlign='left';}

function cloud_arch(canvas){const ctx=canvas.getContext('2d');const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);ctx.fillStyle=C.gold+'22';ctx.strokeStyle=C.gold;ctx.lineWidth=2;roundRect(ctx,W/2-50,8,100,30,8);ctx.fill();ctx.stroke();ctx.fillStyle=C.cream;ctx.font=`bold 10px ${ft}`;ctx.textAlign='center';ctx.fillText('Load Balancer',W/2,28);[{x:.15,label:'AZ-1a',color:C.blue},{x:.5,label:'AZ-1b',color:C.green},{x:.85,label:'AZ-1c',color:C.purple}].forEach((az,i)=>{const x=az.x*W;ctx.beginPath();ctx.moveTo(W/2,38);ctx.lineTo(x,60);ctx.strokeStyle=C.bd;ctx.lineWidth=1;ctx.setLineDash([3,3]);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=az.color+'10';ctx.strokeStyle=az.color+'40';ctx.lineWidth=1;roundRect(ctx,x-52,55,104,H-65,8);ctx.fill();ctx.stroke();ctx.fillStyle=az.color;ctx.font=`bold 10px ${ft}`;ctx.fillText(az.label,x,70);ctx.fillStyle=az.color+'22';ctx.strokeStyle=az.color;roundRect(ctx,x-40,78,80,24,5);ctx.fill();ctx.stroke();ctx.fillStyle=C.cream;ctx.font=`9px ${ft}`;ctx.fillText('App Server',x,94);const dbLabel=i===0?'DB Primary':'DB Replica';ctx.fillStyle=(i===0?C.gold:C.creamF)+'22';ctx.strokeStyle=i===0?C.gold:C.creamF;roundRect(ctx,x-40,110,80,24,5);ctx.fill();ctx.stroke();ctx.fillStyle=C.cream;ctx.fillText(dbLabel,x,126);});ctx.fillStyle=C.creamF;ctx.font=`10px ${ft}`;ctx.fillText('If AZ-1a fails → traffic shifts automatically → zero downtime',W/2,H-6);ctx.textAlign='left';}

export const devopsVisualizations = { devops_lifecycle, vm_vs_container, k8s_architecture, cicd_pipeline, terraform_flow, observability_pillars, cloud_arch };