import React, { useState } from 'react';
import { colors as C, fonts } from '../styles/theme';
export default function DeepDive({ module: mod, apiKey }) {
  const [content,setContent]=useState(null);const [loading,setLoading]=useState(false);const [error,setError]=useState(null);const [quizAns,setQuizAns]=useState(null);
  const generate=()=>{if(!apiKey){setError('Set your Gemini API key first.');return;}setLoading(true);setError(null);
    const topics=mod.sections.filter(s=>s.type==='concept'||s.type==='insight').map(s=>s.title).join(', ');
    fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key='+apiKey,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:'You are a tech educator. Deep-dive for: "'+mod.title+'". Return ONLY JSON: {"title":"...","sections":[{"heading":"...","content":"2-3 paragraphs","realWorldExample":"..."}],"advancedConcepts":["c1","c2","c3"],"practiceChallenge":{"description":"...","steps":["s1","s2","s3"]},"quiz":{"question":"...","options":["a","b","c","d"],"correctIndex":0,"explanation":"..."},"resources":["r1","r2"]} 3 sections. Topics: '+topics}]}],generationConfig:{temperature:0.7,maxOutputTokens:4000}})})
    .then(r=>r.json()).then(data=>{if(data.error)throw new Error(data.error.message);const t=data.candidates?.[0]?.content?.parts?.[0]?.text||'';setContent(JSON.parse(t.replace(/```json|```/g,'').trim()));setLoading(false)}).catch(e=>{setError(e.message);setLoading(false)})};
  if(!content&&!loading&&!error)return<div style={{textAlign:'center',padding:32}}><div style={{fontSize:52,marginBottom:14}}>🔭</div><p style={{fontFamily:fonts.serif,fontSize:22,color:C.cream,marginBottom:24}}>Ready to go deeper?</p><button onClick={generate} style={{fontFamily:fonts.body,fontSize:16,padding:'14px 36px',background:'linear-gradient(135deg,'+C.gold+','+C.accent+')',color:C.bg,border:'none',borderRadius:10,cursor:'pointer',fontWeight:700}}>🔭 Generate Deep Dive</button></div>;
  if(loading)return<div style={{textAlign:'center',padding:48}}><div style={{fontSize:40,animation:'pulse 1.5s infinite'}}>🧠</div><p style={{fontFamily:fonts.body,fontSize:14,color:C.creamD,marginTop:14}}>Generating...</p></div>;
  if(error)return<div style={{textAlign:'center',padding:32}}><p style={{color:C.red,fontFamily:fonts.body,fontSize:13,marginBottom:14}}>{error}</p><button onClick={generate} style={{fontFamily:fonts.body,fontSize:12,padding:'8px 20px',background:'none',border:'1px solid '+C.gold,color:C.gold,borderRadius:6,cursor:'pointer'}}>Try Again</button></div>;
  return<div style={{display:'flex',flexDirection:'column',gap:18}}>
    <h3 style={{fontFamily:fonts.serif,fontSize:22,color:C.gold}}>{content.title}</h3>
    {(content.sections||[]).map((s,i)=><div key={i} style={{background:C.bg,borderRadius:10,padding:18,border:'1px solid '+C.bd}}><h4 style={{fontFamily:fonts.serif,fontSize:17,color:C.goldB,marginBottom:8}}>{s.heading}</h4><p style={{fontFamily:fonts.body,fontSize:13,color:C.creamD,lineHeight:1.7,whiteSpace:'pre-wrap'}}>{s.content}</p>{s.realWorldExample&&<div style={{background:C.hover,padding:10,borderRadius:8,borderLeft:'3px solid '+C.blue,marginTop:10}}><p style={{fontFamily:fonts.body,fontSize:12,color:C.creamD}}>{s.realWorldExample}</p></div>}</div>)}
    {content.practiceChallenge&&<div style={{background:C.bg,borderRadius:10,padding:18,border:'1px solid '+C.bd,borderLeft:'3px solid '+C.green}}><h4 style={{fontFamily:fonts.serif,fontSize:16,color:C.green,marginBottom:8}}>Practice Challenge</h4><p style={{fontFamily:fonts.body,fontSize:13,color:C.creamD,marginBottom:10}}>{content.practiceChallenge.description}</p></div>}
    <button onClick={()=>{setContent(null);setQuizAns(null)}} style={{fontFamily:fonts.body,fontSize:12,padding:'8px 20px',background:'none',border:'1px solid '+C.bd,color:C.creamF,borderRadius:6,cursor:'pointer',alignSelf:'center'}}>🔄 Regenerate</button></div>;
}
